#!/bin/bash

function usage() {
  echo 'usage: git rstash push <stash> [<remote>]'
  echo '   or: git rstash fetch [<remote>]'
}

function push() {
  [ -z "$1" ] && echo 'Error: please specify a stash number to push.' && return 1
  remote=origin
  [ -z "$2" ] || remote="$2"

  echo "Pushing stash $1 to $remote."

  git push $remote stash@{$1}:refs/stashes/$(git rev-parse --short stash@{$1})
}

function fetch() {
  remote=origin
  [ -z "$1" ] || remote="$1"

  git fetch "$remote" refs/stashes/*:refs/stashes/*
}

case "$1" in
  push)
    shift
    push "$@"
    ;;
  fetch)
    shift
    fetch "$@"
    ;;
  -h)
    usage
    exit 0
    ;;
  *)
    usage
    exit 1
    ;;
esac
