#!/bin/bash

function usage() {
  echo 'usage: git rstash push <stash> [<remote>]'
  echo '   or: git rstash fetch [<remote>]'
  echo '   or: git rstash drop <stash> [<remote>]'
}

function push() {
  [ -z "$1" ] && echo 'Error: please specify a stash number to push.' && exit 2
  remote=origin
  [ -z "$2" ] || remote="$2"

  echo "Pushing stash $1 to $remote."

  git push $remote stash@{$1}:refs/stashes/$(git rev-parse --short stash@{$1})
}

function fetch() {
  remote=origin
  [ -z "$1" ] || remote="$1"

  git fetch "$remote" refs/stashes/*:refs/stashes/*
}

function drop() {
  remote=origin
  [ -z "$1" ] && echo 'Error: please specify a stash number to drop.' && exit 3
  stashNum="$1"
  shift
  [ -z "$1" ] || remote="$1"
  stashCommit=$(git rev-parse --short stash@{$stashNum})

  read -p "Really delete stash $stashNum (commit $stashCommit) from $remote? " answer
  if [ "$answer" == 'y' ]
  then
    git push $remote :refs/stashes/$stashCommit
  fi
}

case "$1" in
  push)
    shift
    push "$@"
    ;;
  fetch)
    shift
    fetch "$@"
    ;;
  drop|remove|delete)
    shift
    drop "$@"
    ;;
  -h)
    usage
    exit 0
    ;;
  *)
    usage
    exit 1
    ;;
esac
